version: 2
updates:

# Fetch and update latest `npm` packages
- package-ecosystem: npm
  directory:
#     - '/frontend/angular/'
    - '/frontend/next/'
#     - '/frontend/nuxt/'
#     - '/frontend/react/'
#     - '/frontend/vue/'
#     - '/backend/nodejs/'
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - skwcrd
  assignees:
    - skwcrd
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope

- package-ecosystem: npm
  directory:
#     - '/frontend/angular/'
#     - '/frontend/next/'
    - '/frontend/nuxt/'
#     - '/frontend/react/'
#     - '/frontend/vue/'
#     - '/backend/nodejs/'
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - skwcrd
  assignees:
    - skwcrd
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope

# Fetch and update latest `github-actions` pkgs
- package-ecosystem: github-actions
  directory: '.'
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - skwcrd
  assignees:
    - skwcrd
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
