version: 2
updates:

# Fetch and update latest `npm` packages
- package-ecosystem: npm
  directory: '/frontend/angular/'
  schedule:
    interval: weekly
    time: '00:00'
  open-pull-requests-limit: 0
  reviewers:
    - skwcrd
  assignees:
    - skwcrd
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope

# Fetch and update latest `npm` packages
- package-ecosystem: npm
  directory: '/frontend/next/'
  schedule:
    interval: weekly
    time: '00:00'
  open-pull-requests-limit: 0
  reviewers:
    - skwcrd
  assignees:
    - skwcrd
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope

# Fetch and update latest `npm` packages
- package-ecosystem: npm
  directory: '/frontend/nuxt/'
  schedule:
    interval: weekly
    time: '00:00'
  open-pull-requests-limit: 0
  reviewers:
    - skwcrd
  assignees:
    - skwcrd
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope

# Fetch and update latest `npm` packages
- package-ecosystem: npm
  directory: '/frontend/react/'
  schedule:
    interval: weekly
    time: '00:00'
  open-pull-requests-limit: 0
  reviewers:
    - skwcrd
  assignees:
    - skwcrd
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope

# Fetch and update latest `npm` packages
- package-ecosystem: npm
  directory: '/frontend/vue/'
  schedule:
    interval: weekly
    time: '00:00'
  open-pull-requests-limit: 0
  reviewers:
    - skwcrd
  assignees:
    - skwcrd
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope

# Fetch and update latest `pip` packages
- package-ecosystem: pip
  directory: '/backend/django/'
  schedule:
    interval: weekly
    time: '00:00'
  open-pull-requests-limit: 0
  reviewers:
    - skwcrd
  assignees:
    - skwcrd
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope

# Fetch and update latest `pip` packages
- package-ecosystem: pip
  directory: '/backend/flask/'
  schedule:
    interval: weekly
    time: '00:00'
  open-pull-requests-limit: 0
  reviewers:
    - skwcrd
  assignees:
    - skwcrd
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope

# Fetch and update latest `gomod` packages
- package-ecosystem: gomod
  directory: '/backend/golang/'
  schedule:
    interval: weekly
    time: '00:00'
  open-pull-requests-limit: 0
  reviewers:
    - skwcrd
  assignees:
    - skwcrd
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope

# Fetch and update latest `npm` packages
- package-ecosystem: npm
  directory: '/backend/nodejs/'
  schedule:
    interval: weekly
    time: '00:00'
  open-pull-requests-limit: 0
  reviewers:
    - skwcrd
  assignees:
    - skwcrd
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope

# Fetch and update latest `composer` packages
- package-ecosystem: composer
  directory: '/backend/php/'
  schedule:
    interval: weekly
    time: '00:00'
  open-pull-requests-limit: 0
  reviewers:
    - skwcrd
  assignees:
    - skwcrd
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope

# Fetch and update latest `cargo` packages
- package-ecosystem: cargo
  directory: '/backend/rust/'
  schedule:
    interval: weekly
    time: '00:00'
  open-pull-requests-limit: 0
  reviewers:
    - skwcrd
  assignees:
    - skwcrd
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope

# Fetch and update latest `github-actions` pkgs
- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: weekly
    time: '00:00'
  open-pull-requests-limit: 0
  reviewers:
    - skwcrd
  assignees:
    - skwcrd
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
