version: '3'
services:
    frontend:
        container_name: todo_list_frontend
        build: frontend/angular
        restart: always
        ports:
            - 4000:4000

    backend:
        container_name: todo_list_backend
        build: backend/nodejs
        restart: always
        ports:
            - 3000:3000
        environment:
            MONGO_DB_USERNAME: todo_list-user
            MONGO_DB_PASSWORD: todo_list-password
            MONGO_DB_HOST: database
            MONGO_DB_PORT:
            MONGO_DB_PARAMETERS: "?authSource=admin"
            MONGO_DB: todo_list
        links:
            - database

#     monitor:
#         container_name: todo_list_monitor
#         image: todo_list-monitor
#         ports:
#             - 8081:8081
#         depends_on:
#             - backend

    database:
        container_name: todo_list_database
        image: mongo:latest
        restart: always
        environment:
            MONGO_DATA_DIR: /data/db
            MONGO_LOG_DIR: /dev/null
            MONGO_ROOT_USERNAME: todo_list-user
            MONGO_ROOT_PASSWORD: todo_list-password
            MONGO_DB_USERNAME: todo_list-user
            MONGO_DB_PASSWORD: todo_list-password
            MONGO_DB: todo_list
        volumes:
            - ./database/mongo:/home/mongodb
            - ./database/mongo/init-db.d/:/docker-entrypoint-initdb.d/
            - ./database/mongo/db:/data/db
        ports:
            - 27017:27017

    server:
        container_name: todo_list_server
        build: server/nginx
        restart: always
        ports:
            - "80:80"
        links:
            - frontend
            - backend
