CREATE DATABASE todo_list;

-- CREATE TABLE IF NOT EXISTS users (
--   id INT AUTO_INCREMENT,
--   username TEXT UNIQUE NOT NULL,
--   password TEXT NOT NULL,
--   createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--   updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--   PRIMARY KEY (id)
-- );

-- CREATE TABLE IF NOT EXISTS userInfo (
--   id INT AUTO_INCREMENT,
--   userId INT NOT NULL,
--   firstname TINYTEXT NOT NULL,
--   lastname TINYTEXT NOT NULL,
--   address TEXT NOT NULL,
--   email TEXT NOT NULL,
--   phone TEXT NOT NULL,
--   createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--   updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--   PRIMARY KEY (id)
--   FOREIGN KEY (userId) REFERENCES Users(id)
-- );

CREATE TABLE IF NOT EXISTS todos (
  id INT AUTO_INCREMENT,
  -- authorId INT NOT NULL,
  title TINYTEXT NOT NULL,
  details TEXT NOT NULL,
  isDone BOOL NOT NULL DEFAULT FALSE
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
  -- FOREIGN KEY (authorId) REFERENCES Users(id)
);