name: todo_list
version: 1.0.0
summary: todo_list
description: Todo list application

confinement: strict
base: core18
grade: stable

slots:
  dbus-todo-list: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: com.skwcrd.todo_list # adjust accordingly to your app name and

apps:
  todo_list:
    command: todo_list
    extensions: [ flutter-master ] # Where "master" defines which Flutter channel to use for the build
    plugs:
    - network
    slots:
      - dbus-todo-list
parts:
  todo_list:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application